services:
  mockserver:
    image: mockserver/mockserver:5.15.0
#    healthcheck:
#      test: curl -f localhost:1080/mockserver/health
    command: -logLevel DEBUG -serverPort 1080 -proxyRemotePort 8080 -proxyRemoteHost keycloak
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_MAX_EXPECTATIONS: 200
      MOCKSERVER_MAX_HEADER_SIZE: 8192
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /mockserver/health
      MOCKSERVER_VERBOSE: true
      MOCKSERVER_TRACE: true
