apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-discovery
spec:
  selector:
    app: keycloak
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.5.0
          args: ["start", "--import-realm"]
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/party-realm-realm.json
              name: keycloak-realm-volume
              subPath: party-realm-realm.json
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_URL
              value: "https://it220274.cloud.htl-leonding.ac.at/auth"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_CACHE
              value: ispn
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: '$(POD_IP)'
            - name: KC_DB_URL_DATABASE
              value: 'demo'
            - name: KC_DB_URL_HOST
              value: 'postgres'
            - name: KC_DB
              value: 'postgres'
            - name: KC_DB_PASSWORD
              value: 'demo'
            - name: KC_DB_USERNAME
              value: 'demo'
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 1700Mi
      volumes:
        - name: keycloak-realm-volume
          configMap:
            name: keycloak-realm-config
