apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: quarkus
          env:
          - name: QUARKUS_PROFILE
            value: prod
          - name: KEYCLOAK_ISSUER
            value: "https://it220274.cloud.htl-leonding.ac.at/keycloak/realms/partyhub"
          envFrom:
          - secretRef:
              name: partyhub-smtp-secret
          image: ghcr.io/htl-leo-itp-25-27-4-5bhitm/partyhub-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: profile-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30801
  selector:
    app: quarkus
