@startuml
title Der Weg zur Schule
start
:Wecker klingelt;
:Wecker klingelt 2. Mal;
:Aufstehen;
:Klo gehen;
:Anziehen;
:Essen;
:Schulsachen in Schultasche tun;
:Zähne putzen / Waschen / Haare machen;
:Schuhe anziehen / Jacke;
:Zum Auto gehen;
:Mit dem Auto zur schule gefahren werden;
:Zur Schule gehen;
:In der Schule angekommen;
stop
@enduml