@REALM={{KEYCLOAK_URL}}/realms/demo

# open http://localhost:8000/admin/master/console/#/demo/clients/ and navigate to backend->credentials and paste here
@CLIENT_SECRET=o1BWGJt5QlS0D3yn9HtLXXWI5W6DqjxL

###
# @name clear all
PUT {{MOCKSERVER}}/clear?type=log
###

###
# @name wellknown
GET {{REALM}}/.well-known/openid-configuration
?? status == 200
###
# @ref wellknown
# @name login
POST {{wellknown.token_endpoint}}
Content-Type: application/x-www-form-urlencoded

client_secret={{CLIENT_SECRET}}&client_id=backend&username=joe&password=password&grant_type=password&redirect_uri=http%3A%2F%2Fwww.htl-leonding.ac.at&scope=openid

?? status == 200
{{
    console.log(`Authorization: ${response.parsedBody.access_token} Bearer`, response.parsedBody.access_token)
}}
###
# @ref wellknown
# @name userinfo
GET {{wellknown.userinfo_endpoint}}
Authorization: Bearer {{login.access_token}}
Accept: application/json


### hello ###
# @name hello
GET {{BACKEND_URL}}/hello

?? status == 200
###
# @ref login
# @name posts
GET {{BACKEND_URL}}/posts
Content-Type: application/json
Authorization: Bearer {{login.access_token}}

?? status == 200

###
# @ref wellknown
# @name loginform
GET {{wellknown.authorization_endpoint}}?response_type=code&client_id=frontend&redirect_uri=http%3A%2F%2Flocalhost%3A8888&scope=openid

{{
    const parser = require('node-html-parser')
    const document = parser.parse(response.body)
    const form = document.querySelector("form")
    $global.action = form.getAttribute("action")

    console.log("=====================")
    console.log("action", $global.action)
    console.log("=====================")

    const allCookies = response
        .headers["set-cookie"]
        .map(cookie => cookie.split(";"))
        .map(details => details[0])
        .join("; ")
    console.log("cookie:\n", allCookies)
    $global.cookie = allCookies
}}
###
# @ref loginform
# @name submit
## not possible, see https://github.com/whatwg/fetch/issues/763
{{
    const action = $global.action
    console.log("=====================")
    console.log("action", action)
    console.log("=====================")
    console.log("this request will fail, because the redirect is followed automatically and there is no server")
}}
POST {{$global.action}}
Content-Type: application/x-www-form-urlencoded
Cookie: {{$global.cookie}}

username=joe&password=password&id-hidden-input=
{{
    console.log("this request failed, because the redirect is followed automatically and there is no server")
}}
###
# @title Report of Keycloak Requests
# @description the Mock Server stored the requests to keycloak, this is the summary
# @name logKeycloakRequests
PUT {{MOCKSERVER}}/retrieve?type=logs&format=json
#PUT {{MOCKSERVER}}/retrieve?type=REQUEST_RESPONSES

###
# @name open login dialog
GET https://auth.htl-leonding.ac.at/realms/leocloud/account
###