-- Baseline: the PartyHub schema as produced by the Hibernate entities (Quarkus 3.28.2)
-- on PostgreSQL 16, generated with pg_dump --schema-only --no-owner from a drop-and-create
-- database and trimmed to PartyHub tables, sequences and constraints.
-- Existing databases are baselined at version 1 and skip this file (baseline-on-migrate).
-- Never edit an applied migration; add a new V<n>__*.sql instead.

CREATE TABLE public.follow (
    status_id bigint NOT NULL,
    user1_id bigint NOT NULL,
    user2_id bigint NOT NULL
);

CREATE TABLE public.follow_status (
    id bigint NOT NULL,
    name character varying(255)
);

CREATE TABLE public.invitation (
    id bigint NOT NULL,
    party_id bigint,
    recipient_id bigint,
    sender_id bigint,
    status character varying(255) NOT NULL
);

ALTER TABLE public.invitation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.location (
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    id bigint NOT NULL,
    address character varying(255)
);

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.media (
    id bigint NOT NULL,
    party_id bigint,
    user_id bigint,
    file character varying(255)
);

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notification (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    party_id bigint,
    recipient_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    message character varying(255) NOT NULL,
    status character varying(255) NOT NULL
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.party (
    fee double precision,
    max_age integer,
    max_people integer,
    min_age integer,
    created_at timestamp(6) without time zone NOT NULL,
    host_user_id bigint,
    id bigint NOT NULL,
    location_id bigint NOT NULL,
    time_end timestamp(6) without time zone,
    time_start timestamp(6) without time zone,
    description character varying(255),
    theme character varying(255),
    title character varying(255),
    visibility character varying(255) NOT NULL,
    website character varying(255)
);

ALTER TABLE public.party ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.party_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.party_user (
    party_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.profile_picture (
    id bigint NOT NULL,
    user_id bigint,
    picture_name character varying(255)
);

ALTER TABLE public.profile_picture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_picture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.qr_login (
    used boolean NOT NULL,
    expiresat timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    mobiletokenexpiresat timestamp(6) with time zone,
    userid bigint NOT NULL,
    mobiletoken character varying(255),
    token character varying(255) NOT NULL
);

ALTER TABLE public.qr_login ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qr_login_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_location (
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    id bigint NOT NULL,
    user_id bigint
);

ALTER TABLE public.user_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_notification_settings (
    email_enabled boolean NOT NULL,
    follow_events boolean NOT NULL,
    in_app_enabled boolean NOT NULL,
    party_invites boolean NOT NULL,
    party_updates boolean NOT NULL,
    push_enabled boolean NOT NULL,
    sms_enabled boolean NOT NULL,
    id bigint NOT NULL
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    biography character varying(255),
    device_token character varying(255),
    display_name character varying(255),
    distinct_name character varying(255),
    email character varying(255),
    keycloak_id character varying(255),
    phone_number character varying(255),
    username character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT follow_pkey PRIMARY KEY (user1_id, user2_id);

ALTER TABLE ONLY public.follow_status
    ADD CONSTRAINT follow_status_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT invitation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.party
    ADD CONSTRAINT party_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.party_user
    ADD CONSTRAINT party_user_pkey PRIMARY KEY (party_id, user_id);

ALTER TABLE ONLY public.profile_picture
    ADD CONSTRAINT profile_picture_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profile_picture
    ADD CONSTRAINT profile_picture_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY public.qr_login
    ADD CONSTRAINT qr_login_mobiletoken_key UNIQUE (mobiletoken);

ALTER TABLE ONLY public.qr_login
    ADD CONSTRAINT qr_login_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.qr_login
    ADD CONSTRAINT qr_login_token_key UNIQUE (token);

ALTER TABLE ONLY public.user_location
    ADD CONSTRAINT user_location_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_location
    ADD CONSTRAINT user_location_user_id_key UNIQUE (user_id);

ALTER TABLE ONLY public.user_notification_settings
    ADD CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_keycloak_id_key UNIQUE (keycloak_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk1ow43xgi26y0ul2obtddwqpj7 FOREIGN KEY (party_id) REFERENCES public.party(id);

ALTER TABLE ONLY public.user_notification_settings
    ADD CONSTRAINT fk87nt2aqdmispu1y3r5nfgpwwe FOREIGN KEY (id) REFERENCES public.users(id);

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT fk8qamsp0em5ub7edqfww44h3ix FOREIGN KEY (sender_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT fka0syf9tpw0a5dghn6b7vejjdd FOREIGN KEY (status_id) REFERENCES public.follow_status(id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkfcyn9rsga73dqnorl7owfyl4a FOREIGN KEY (recipient_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT fkfhxr1mt3nm6rst91nv9nfgcl7 FOREIGN KEY (recipient_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.media
    ADD CONSTRAINT fkglx89bh4djt6vn8jpm3w2fdoa FOREIGN KEY (party_id) REFERENCES public.party(id);

ALTER TABLE ONLY public.profile_picture
    ADD CONSTRAINT fkhaqog2xkjc6oouv5wgeyxnlnt FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_location
    ADD CONSTRAINT fkjxhhctinrouub93yin6vgvqr4 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.party
    ADD CONSTRAINT fkmowk135ni2n7uf14qiue05a9u FOREIGN KEY (host_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.media
    ADD CONSTRAINT fknd8hh0yn7qvv4pqyk8mg7l1ox FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.invitation
    ADD CONSTRAINT fknrbb5mvl11htfioxhu4ej5ck3 FOREIGN KEY (party_id) REFERENCES public.party(id);

ALTER TABLE ONLY public.party_user
    ADD CONSTRAINT fkoatbt6tv26kk2r5vgua7ojsm FOREIGN KEY (party_id) REFERENCES public.party(id);

ALTER TABLE ONLY public.party_user
    ADD CONSTRAINT fkq5094wl2cet4y5vwsq5294uun FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkrg0atx075rr68et2rqrh34qwj FOREIGN KEY (sender_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.party
    ADD CONSTRAINT fktjo02uqqgf57kvbdklalp9gvt FOREIGN KEY (location_id) REFERENCES public.location(id);

