###
GET http://localhost:8080/follow/follower/1/count

?? status == 200

<> 2026-03-04T092555.200.json

###
GET http://localhost:8080/follow/following/1/count

?? status == 200


###
GET http://localhost:8080/follow/followers/1

?? status == 200

<> 2026-03-04T093442.200.json


###
GET http://localhost:8080/follow/followings/2

?? status == 200

<> 2026-03-04T093921.200.json
###
GET http://localhost:8080/follow/pending/1

?? status == 200

<> 2026-03-04T094645.200.json
###
GET http://localhost:8080/follow/is-following/1/2

?? status == 200

<> 2026-03-04T094843.200.json

###
POST http://localhost:8080/follow/request/2/3

?? status == 201

<> 2026-03-04T095004.200.json

###
POST http://localhost:8080/follow/request/1/7

?? status == 201