# Follow endpoints - under /api/users/{id}/*
# Paths must match UserResource.java implementation

###########################################
### 1. Follower Count
###########################################
GET http://localhost:8080/api/users/1/followers/count

?? status == 200


###########################################
### 2. Following Count
###########################################
GET http://localhost:8080/api/users/1/following/count

?? status == 200


###########################################
### 3. Get followers of user
###########################################
GET http://localhost:8080/api/users/1/followers

?? status == 200


###########################################
### 4. Get following of user
###########################################
GET http://localhost:8080/api/users/2/following

?? status == 200


###########################################
### 5. Get pending follow requests
###########################################
GET http://localhost:8080/api/users/1/follow-requests

?? status == 200


###########################################
### 6. Check if user1 is following user2 (status endpoint)
###########################################
GET http://localhost:8080/api/users/1/followers/2/status

?? status == 200


###########################################
### 7. Send follow request (user 2 wants to follow user 3)
###########################################
POST http://localhost:8080/api/users/2/follow?targetUserId=3

?? status == 201


###########################################
### 8. Accept follow request (user 3 accepts user 2's request)
###########################################
PUT http://localhost:8080/api/users/3/followers/2

?? status == 200


###########################################
### 9. Remove follow (user 1 unfollows user 7)
### Note: Returns 404 if no relationship exists
###########################################
DELETE http://localhost:8080/api/users/1/followers/7

?? status == 404


###########################################
### 10. Decline follow request (reject pending request)
### User 6 has pending request to follow user 1
### To decline: DELETE /api/users/{recipientId}/followers/{followerId}
###########################################
DELETE http://localhost:8080/api/users/1/followers/6

?? status == 204


###########################################
### 11. Accept follow request (confirm pending request)
### First create a pending request: user 7 wants to follow user 1
###########################################
POST http://localhost:8080/api/users/7/follow?targetUserId=1

?? status == 201

# Accept: PUT /api/users/{recipientId}/followers/{followerId}
PUT http://localhost:8080/api/users/1/followers/7

?? status == 200
