@host = http://localhost:8080
@baseUrl = {{host}}/api/invitations

###########################################
### Seed: Michael received invitation 1 for private party 4
###########################################
GET {{baseUrl}}?user=2&direction=received

?? status == 200


###########################################
### Seed: Thomas sent invitations for private party 4
###########################################
GET {{baseUrl}}?user=4&direction=sent

?? status == 200


###########################################
### Seed: Anna received invitation 3 for private party 9
###########################################
GET {{baseUrl}}?user=1&direction=received

?? status == 200


###########################################
### User is required
###########################################
GET {{baseUrl}}

?? status == 400


###########################################
### Only sender or recipient may delete an invitation
###########################################
DELETE {{baseUrl}}/1?user=5

?? status == 403


###########################################
### Unknown invitation returns 404
###########################################
DELETE {{baseUrl}}/99999?user=8

?? status == 404
