# Media endpoints - nested under parties/users
# Note: Direct media endpoints by ID may not exist - use party/user media instead

###########################################
### 1. Get party media (from party endpoint)
###########################################
GET http://localhost:8080/api/parties/2/media

?? status == 200


###########################################
### 2. Get user media (from user endpoint)
###########################################
GET http://localhost:8080/api/users/2/media

?? status == 200
