###
# GET media by ID - returns 404 when not found
GET http://localhost:8080/api/media/2



###
GET http://localhost:8080/api/media/party/2/all

?? status == 200

###
GET http://localhost:8080/api/media/user/2/all

?? status == 200