@baseUrl = http://localhost:8080/api/parties
@partyId = 11

###########################################
### 1. Create Party (Anna erstellt eine Party)
###########################################
POST {{baseUrl}}
X-User-Id: 1
Content-Type: application/json

{
  "title": "Test Party",
  "description": "Party zum Testen",
  "fee": 10.0,
  "time_start": "2026-03-10T20:00:00",
  "time_end": "2026-03-10T23:00:00",
  "website": "https://party.example.com",
  "min_age": 18,
  "max_age": 99,
  "latitude": 48.2082,
  "longitude": 16.3738,
  "location_address": "Wien, Österreich",
  "visibility": "PUBLIC"
}

?? status == 201


###########################################
### 2. Get all parties (Header für Personalisierung)
###########################################
GET {{baseUrl}}
X-User-Id: 1

?? status == 200


###########################################
### 3. Get Party by ID
###########################################
GET {{baseUrl}}/1
X-User-Id: 1

?? status == 200


###########################################
### 4. Update Party (Michael Wagner (2) bearbeitet Party 1)
###########################################
PUT {{baseUrl}}/1
X-User-Id: 2
Content-Type: application/json

{
  "title": "Updated Test Party",
  "description": "Updated Description",
  "fee": 15.0,
  "time_start": "2026-03-11T20:00:00",
  "time_end": "2026-03-11T23:00:00",
  "website": "https://party-updated.example.com",
  "min_age": 18,
  "max_age": 99,
  "latitude": 48.2082,
  "longitude": 16.3738,
  "location_address": "Wien, Österreich",
  "visibility": "PUBLIC"
}

?? status == 200


###########################################
### 7. Check if user can edit party
###########################################
GET {{baseUrl}}/1/can-edit
X-User-Id: 2

?? status == 200


###########################################
### 8. Media Upload
###########################################
POST {{baseUrl}}/2/media/upload
X-User-Id: 3
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testing.jpg"
Content-Type: image/jpeg

< ./testing.jpg
--boundary--

?? status == 200

###########################################
### 11. Filter (Header oft nötig für Sichtbarkeit)
###########################################
GET {{baseUrl}}?q=Linz
X-User-Id: 1

?? status == 200