
###
POST http://localhost:8080/api/party/add
Content-Type: application/json

{
  "title": "testing",
  "description": "testing",
  "fee": 0,
  "time_start": "2026-02-25T15:00:00",
  "time_end": "2026-02-25T16:00:00",
  "max_people": 0,
  "min_age": 0,
  "max_age": 0,
  "website": "",
  "latitude": 0,
  "longitude": 0,
  "location_address": "",
  "category_id": 0,
  "theme": "",
  "visibility": "",
  "selectedUsers": []
}

###
GET http://localhost:8080/api/party/1?
    filter={{$random.alphanumeric(8)}}&
    sort={{$random.alphanumeric(8)}}
    Content-Type: application/json

###
DELETE http://localhost:8080/api/party/6?
    sort={{$random.alphanumeric(8)}}&
    filter={{$random.alphanumeric(8)}}
    Content-Type: application/json

###
POST http://localhost:8080/api/party/5?sort={{$random.alphanumeric(8)}}&filter={{$random.alphanumeric(8)}}
Content-Type: application/json

{
  "title": "HTL Release Party",
  "description": "Feiern ohne NullPointerExceptions",
  "fee": 5.0,
  "time_end": "2026-03-01T04:00:00",
  "website": "https://htl-leonding.ac.at",
  "max_age": 25,
  "min_age": 16,
  "latitude": 48.2683,
  "longitude": 14.2518
}

###
POST http://localhost:8080/api/party/filter?filter=category
Content-Type: application/json

{
  "value": "Musik"
}

###
GET http://localhost:8080/api/party/sort?
    sort={{$random.alphanumeric(8)}}

###
POST http://localhost:8080/api/party/5/attend