@host = http://localhost:8080
@baseUrl = {{host}}/api/users
@anna = 1
@michael = 2
@sabine = 5
@mia = 7

############################################
#### GET: Profile picture for Anna (Seed/Default)
############################################
GET {{baseUrl}}/{{anna}}/profile-picture

?? status === 200
?? headers["Content-Type"] !== undefined


############################################
#### GET: Profile picture for Sabine
############################################
GET {{baseUrl}}/{{sabine}}/profile-picture

?? status === 200
?? headers["Content-Type"] !== undefined


############################################
#### GET: Profile picture for Mia
############################################
GET {{baseUrl}}/{{mia}}/profile-picture

?? (status === 200 || status === 404)


############################################
#### GET: Profile picture filename for Anna
############################################
GET {{baseUrl}}/{{anna}}/profile-picture-filename

?? status === 200


############################################
#### GET: Profile picture filename for Mia
############################################
GET {{baseUrl}}/{{mia}}/profile-picture-filename

?? (status === 200 || status === 204)


############################################
#### GET: Unknown user profile picture
############################################
GET {{baseUrl}}/99999/profile-picture

?? status === 404


############################################
#### POST: Upload profile picture for Sabine
############################################
POST {{baseUrl}}/{{sabine}}/upload-profile-picture
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-User-Id: {{sabine}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testing.jpg"
Content-Type: image/jpeg

< ./testing.jpg
--WebAppBoundary--

?? (status === 200 || status === 201)


############################################
#### DELETE: Remove profile picture for Sabine
############################################
DELETE {{baseUrl}}/{{sabine}}/profile-picture
X-User-Id: {{sabine}}

?? (status === 200 || status === 204)


############################################
#### PUT: Update profile picture for Anna
############################################
PUT {{baseUrl}}/{{anna}}/profile-picture
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-User-Id: {{anna}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testing.jpg"
Content-Type: image/jpeg

< ./testing.jpg
--WebAppBoundary--

?? status === 200
