@searchName = anna
@searchResultId = 1

###
GET http://localhost:8080/api/users/all

?? status == 200

### Search users by name
# @name searchUsersByName
GET http://localhost:8080/api/users/all/search?name={{searchName}}

?? status == 200

###
GET http://localhost:8080/api/users/{{searchResultId}}

?? status == 200
### User direkt per ID holen
GET http://localhost:8080/api/users/1
?? status == 200

### 
GET http://localhost:8080/api/users/handle/anna_huber
Accept: application/json

?? status == 200

###

### Follower Count von User 1
GET http://localhost:8080/api/users/1/followers/count

?? status == 200


### Following Count von User 3
GET http://localhost:8080/api/users/3/following/count

?? status == 200

### User anlegen
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "displayName": "Max Mustermann",
  "distinctName": "max_m",
  "email": "max.mustermann@test.at",
  "biography": "Neuer User"
}

?? status == 201


### 
PUT http://localhost:8080/api/users/5
Content-Type: application/json

{
  "id": 5,
  "displayName": "Sabine Weber",
  "distinctName": "sabine_w",
  "email": "sabine.weber@wien.at",
  "biography": "Immer auf der Suche nach neuen Events"
}

?? status == 200